baseURL = "https://simo-hue.github.io/"
languageCode = "en-us"
title = "Simone Mattioli"
defaultContentLanguage = "en"
theme = "hugo-theme-stack"

[pagination]
pagerSize = 10

disqusShortname = "simo-hue"
hasCJKLanguage = false
uglyURLs = false

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "aws-website"