baseURL = "https://simo-hue.github.io/01_home/simone-mattioli/"
languageCode = "en-us"
title = "Simone Mattioli"
defaultContentLanguage = "en"
theme = "hugo-theme-stack"

[pagination]
pagerSize = 10

disqusShortname = "simo-hue"
hasCJKLanguage = false
uglyURLs = false

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "aws-website"

[outputs]
home = ["HTML", "RSS", "Redirect"]

[outputFormats]
[outputFormats.Redirect]
mediaType = "text/html"
baseName = "index"
isPlainText = true
notAlternative = true
