homepage = "whoami"

# Change baseurl before deploy
baseurl = "https://simo-hue.github.io"
languageCode = "en-us"
theme = "stack"
paginate = 5
title = "Simone Mattioli"

hasCJKLanguage = false
disqusShortname = "simonemattioli"
uglyURLs = true

# ---------------------
# Configurazione Generale del Tema Stack
# ---------------------

[params]
  author = "Simone Mattioli"
  description = "Web Developer, appassionato di montagna e bio-segnali"
  homepage = "whoami"  # Collegamento alla pagina "Chi Sono"
  profilePicture = "/images/profile.jpg"  # Aggiorna con il percorso della tua immagine profilo
  
  # Configurazione Sidebar
  sidebarLogo = true     # Visualizza il logo o immagine nella sidebar
  enableLightbox = true  # Attiva la lightbox per le immagini
  showReadingTime = true # Mostra il tempo di lettura dei post
  showDate = true        # Mostra la data di pubblicazione
  
  # Social Media Integration
  showSocial = true      # Mostra le icone social nella sidebar

  # Impostazioni aggiuntive per i Post
  enableComments = true  # Abilita i commenti
  showTableOfContents = true # Abilita la visualizzazione dell'indice dei contenuti nei post

  # SEO e OpenGraph
  keywords = ["Simone Mattioli", "Web Developer", "Biomedico", "Montagna"]
  showCanonicalURL = true  # Mostra l'URL canonico per ogni pagina

  # Configurazione del Menu
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[social]
  github = "https://github.com/simo-hue"
  youtube_simosdiary = "https://www.youtube.com/@SimosDiary"
  youtube_mountainfaunalover = "https://www.youtube.com/@mountainfaunalover"

[markup]
  [markup.highlight]
    codeFences = true       # Evidenziazione della sintassi nel codice
    guessSyntax = true      # Rilevamento automatico della sintassi
  [markup.tableOfContents]
    startLevel = 2          # Livello di intestazione per l'indice dei contenuti
    endLevel = 3
    ordered = false