# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/simo-hue"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/simone-mattioli-581633212/"

[social.params]
icon = "brand-linkedin"


[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com/simo___one"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "youtube"
name = "Youtube"
url = "https://youtube.com/@SimosDiary2003"

[social.params]
icon = "brand-youtube"


