baseURL = 'https://github.com/simo-hue/Simone-Mattioli/'
languageCode = 'en-us'
title = 'Mattioli Simone'
theme = "hugo-theme-stack"

[params.sidebar]
  
  emoji = "👨🏽‍💻"
  social = [
    { name = "LinkedIn", url = "https://www.linkedin.com/in/simone-mattioli-581633212/" },
    { name = "Personal YouTube", url = "https://www.youtube.com/@SimosDiary2003" },
    { name = "Instagram", url = "https://www.instagram.com/simo___one" }
  ]